const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

console.log("Restoring base layer from strict fixes...");
execSync('node apply_all_fixes_strict.js', { stdio: 'inherit' });

console.log("Applying sidebar UI overrides...");
execSync('node fix_sidebar_height.js', { stdio: 'inherit' });

console.log("Applying Light Mode contrasts...");
execSync('node fix_lightmode_text.js', { stdio: 'inherit' });

console.log("Applying Mobile Overflow fix...");
execSync('node fix_mobile_overflow.js', { stdio: 'inherit' });

console.log("Applying True Exact-Match Logo Swapper...");
let content = fs.readFileSync('curso_veo.html', 'utf8');

// The standard logos generated by apply_all_fixes_strict.js
const badDarkLogo = `<img src="assets/image.png" alt="Turing Logo" class="h-10 sm:h-12 w-10 sm:w-12 object-contain dark:hidden filter drop-shadow-[0_0_5px_rgba(0,0,0,0.1)]" onerror="this.src='https://via.placeholder.com/150?text=Logo'">`;
const badLightLogo = `<img src="assets/Logoblanco.png" alt="Turing Logo" class="hidden h-10 sm:h-12 w-10 sm:w-12 object-contain dark:block filter drop-shadow-[0_0_10px_rgba(230,57,70,0.8)]" onerror="this.src='https://via.placeholder.com/150?text=Logo'">`;

const goodLightLogo = `<img src="assets/Logoblanco.png" alt="Turing Logo" class="h-10 sm:h-12 w-10 sm:w-12 object-contain dark:hidden filter drop-shadow-[0_0_5px_rgba(0,0,0,0.1)]" onerror="this.src='https://via.placeholder.com/150?text=Logo'">`;
const goodDarkLogo = `<img src="assets/image.png" alt="Turing Logo" class="hidden h-10 sm:h-12 w-10 sm:w-12 object-contain dark:block filter drop-shadow-[0_0_10px_rgba(230,57,70,0.8)]" onerror="this.src='https://via.placeholder.com/150?text=Logo'">`;

// Replace desktop ones
content = content.replace(badDarkLogo, goodLightLogo);
content = content.replace(badLightLogo, goodDarkLogo);

// The mobile header logos might have different sizes
const badDarkLogoMob = `<img src="assets/image.png" alt="Turing Logo" class="h-10 w-10 object-contain dark:hidden filter drop-shadow-[0_0_5px_rgba(0,0,0,0.1)]" onerror="this.src='https://via.placeholder.com/150?text=Logo'">`;
const badLightLogoMob = `<img src="assets/Logoblanco.png" alt="Turing Logo" class="hidden h-10 w-10 object-contain dark:block filter drop-shadow-[0_0_10px_rgba(230,57,70,0.8)]" onerror="this.src='https://via.placeholder.com/150?text=Logo'">`;

const goodLightLogoMob = `<img src="assets/Logoblanco.png" alt="Turing Logo" class="h-10 w-10 object-contain dark:hidden filter drop-shadow-[0_0_5px_rgba(0,0,0,0.1)]" onerror="this.src='https://via.placeholder.com/150?text=Logo'">`;
const goodDarkLogoMob = `<img src="assets/image.png" alt="Turing Logo" class="hidden h-10 w-10 object-contain dark:block filter drop-shadow-[0_0_10px_rgba(230,57,70,0.8)]" onerror="this.src='https://via.placeholder.com/150?text=Logo'">`;

content = content.replace(badDarkLogoMob, goodLightLogoMob);
content = content.replace(badLightLogoMob, goodDarkLogoMob);


// NOW! Let's ensure the `loadingOverlay` and `appContainer` exist in the DOM AND import the auth properly!
// We will wrap the inside of `<body>` with `<div id="appContainer" style="display:none;" class="w-full flex">` 
// and inject the `<div id="loadingOverlay">` at the start.

if (content.indexOf(`id="appContainer"`) === -1) {
    const bodyMatch = content.match(/<body[^>]*>/);
    if (bodyMatch) {
        const overlayHTML = `
<!-- Overlay de Carga Principal -->
<div id="loadingOverlay" class="fixed inset-0 z-[100] bg-turingDark flex flex-col items-center justify-center transition-opacity duration-500">
    <div class="flex flex-col items-center">
        <i class="fa-solid fa-circle-notch fa-spin text-5xl text-turingRed mb-4 drop-shadow-[0_0_15px_rgba(230,57,70,0.8)]"></i>
        <h2 class="text-xl font-bold text-white tracking-widest ts-title">Turing Store</h2>
        <p class="text-sm text-gray-400 mt-2">Verificando acceso a Veo...</p>
    </div>
</div>
<!-- Wrap App -->
<div id="appContainer" style="display: none;" class="w-full relative">
`;
        // Insert right after body tag
        content = content.replace(bodyMatch[0], bodyMatch[0] + "\n" + overlayHTML);
        // Add closing div for appContainer right before </body> or right before <script> block for DOM
        // We'll append it before the first <script> tag at the bottom
        const scriptMatch = content.lastIndexOf('<script>');
        if (scriptMatch !== -1) {
            content = content.substring(0, scriptMatch) + '\n</div>\n' + content.substring(scriptMatch);
        }
    }
}

// Ensure the Authentication Script is cleanly appended to the body
const authScript = `
    document.addEventListener('DOMContentLoaded', () => {
      import('./auth-helper.js?v=6').then(async ({ checkAuth }) => {
        try {
            const sessionAuth = await checkAuth(true);
            if (!sessionAuth) return;
            
            const { userData } = sessionAuth;
            const bypass = localStorage.getItem('admin_bypass') === 'true';
            
            if (!bypass && !(userData?.purchased_products || []).includes("GEM-005")) {
                alert("No tienes acceso a este Curso. Serás redirigido.");
                window.location.href = 'dashboard.html';
                return;
            }

            const overlay = document.getElementById('loadingOverlay');
            if(overlay) overlay.style.display = 'none';
            const app = document.getElementById('appContainer');
            if(app) {
                app.style.display = 'flex';
                // Make sure mobile handles flex cols
                if(window.innerWidth < 1024) { app.style.flexDirection = 'column'; }
            }
            
            loadProgress();
            if (typeof currentLesson === 'undefined' || currentLesson < 1) showVideo(1);
        } catch (error) {
            console.error(error);
            const overlay = document.getElementById('loadingOverlay');
            if(overlay) overlay.style.display = 'none';
            const app = document.getElementById('appContainer');
            if(app) {
                app.style.display = 'flex';
                if(window.innerWidth < 1024) { app.style.flexDirection = 'column'; }
            }
            loadProgress();
            if (typeof currentLesson === 'undefined' || currentLesson < 1) showVideo(1);
        }
      });
    });
`;

if (content.indexOf(`import('./auth-helper.js?v=6')`) === -1) {
    const bottomScriptPlacement = content.lastIndexOf('</script>');
    content = content.substring(0, bottomScriptPlacement) + authScript + content.substring(bottomScriptPlacement);
}

fs.writeFileSync('curso_veo.html', content);
console.log("Master build applied cleanly without black screens.");
